language: scala
sudo: false
jdk: oraclejdk8
scala:
- 2.12.1
notifications:
  slack:
    secure: C+UMkD+eaaeTJvbEa82vdmNMvFpLgncLU7KDCy+5fUk0Nb1rUVxQ4GrYuqBUDC9g3OvVmKpn3KwCywcohuMMMVsxeHY4tpuUdyjfZSjxnf53TgJk6rBtH0zvMAy57RXJ1AUIyHmIH8jMF3LEAlRDAI3bVd84V6ej4GO3OK0ii79vDdRxuHUxnPN8JCYF8pspSrUp9DahR0asCNBswDCNhIAw5k9y0vABXseVzqLBsvfTWLZ9ZbuN3h0Zjh4j0YP4UHUm7JRp845zBbaStNHEss8DhG0dyKZR/nDuWcSzlfscJ+HnIGrgTIX7XNRZwvVuVtbOPvhS6MPm6XdX2oVL4lXG4HP/FEp4LDt0zJ+v8l+wfaW+uQkOR52a+MTVWYcWD9zOq/T01Z48oCV8sEAPP9LmUrjMH4gGb4iXwUniBLZGqra6NHu7sBZ2LKeHzVX483KAbSdcChaUV8uHPf0CmVN37Jq1LDmGVGmE6F9tRDy3amypTXKSpuyo6HqHZogrP1NO2wkxZ4/tb7hT4n/ie74pQOaioVUvX2n1xnZccxZUdfLczDhBADLFK/ekRx+KnmG0CCD3C41lCxAqSo270d39qm0k2NN3P9hYuI6nEBypLzWnbdEOx4i67Tt15Qab3QCI2W0IOxO+fL4eANXZjqkIfjH9+BPiOBNyYlpOnPU=
deploy:
  provider: bintray
  on:
    all_branches: true
  user: "patricknoir"
  key:
    secure: YJGZkDY5NU9IlekJhaOjIzR9i68+JGxwFT2KsUorOX65mwo75NR0ebdkXaQdbwytyp9p1kKC23g/yh6DY7A96gMZqUF7fkDGGdEMOqUYW1hqpL2L6SsQapgy5dAy0QNUXtRYjODCMwA6H4eELIeiNcnGNW4esjUyXEcQBiTM67ps4TlIv096Mq8V9aU2yu1Gm6r1M/DEAI4l8HACDmEDDn9YBlJpUmMbHLyUoJkM3OtEy6Q2vcZ+vhYg/uyBa9C5/zHbg/ToWGxMbZsa1JBQkfQZmYk1kNSlN4P9i1UMEFrh9jXlPrNgM7Vh4qXyVQZQOEWK6JM+AaA2efCduXoKTTWJMIsfPX7VDMIXxF0LzkKt0nHfZwjZwfe/v1zx/a9S3Y6RPeL1kUKH1chz9wcrd2z7SNmM3JpErVgmOi/h/iuL84ssyIC28xYZPloxANV7ArOW2GL6u0uEWElJE1IVvSW3MMp54yj5xJg0niN0jZt3053mha2qE9uQibU86tpejV4bwUQvy1ox9BcBjMEuaI/UjYlThg/+EyUxOugyUcJILaw7KDXzILjTSxzyk52buPHvb9N1WFs6DTigOXvYS0uyvHD44afOGz5Sf2k4a+vjd3Mabr1ZuoDfP9VlyngxfrBVehPWb/4UYQSVl7yRFfTVjFDFZQOncT3fsL9GsvY=
